export const GOLF_COURSE_LIST_REQUEST = 'GOLF_COURSE_LIST_REQUEST'
export const GOLF_COURSE_LIST_SUCCESS= 'GOLF_COURSE_LIST_SUCCESS'
export const GOLF_COURSE_LIST_FAIL= 'GOLF_COURSE_LIST_FAIL'

export const GOLF_COURSE_DETAILS_REQUEST = 'GOLF_COURSE_DETAILS_REQUEST'
export const GOLF_COURSE_DETAILS_SUCCESS= 'GOLF_COURSE_DETAILS_SUCCESS'
export const GOLF_COURSE_DETAILS_FAIL= 'GOLF_COURSE_DETAILS_FAIL'

export const GOLF_COURSE_HOLE_DETAILS_REQUEST = 'GOLF_COURSE_HOLE_DETAILS_REQUEST'
export const GOLF_COURSE_HOLE_DETAILS_SUCCESS= 'GOLF_COURSE_HOLE_DETAILS_SUCCESS'
export const GOLF_COURSE_HOLE_DETAILS_FAIL= 'GOLF_COURSE_HOLE_DETAILS_FAIL'

export const GOLF_COURSE_TEE_DETAILS_REQUEST = 'GOLF_COURSE_TEE_DETAILS_REQUEST'
export const GOLF_COURSE_TEE_DETAILS_SUCCESS= 'GOLF_COURSE_TEE_DETAILS_SUCCESS'
export const GOLF_COURSE_TEE_DETAILS_FAIL= 'GOLF_COURSE_TEE_DETAILS_FAIL'

export const GOLF_COURSE_CREATE_REQUEST = 'GOLF_COURSE_CREATE_REQUEST'
export const GOLF_COURSE_CREATE_SUCCESS = 'GOLF_COURSE_CREATE_SUCCESS'
export const GOLF_COURSE_CREATE_FAIL = 'GOLF_COURSE_CREATE_FAIL'
export const GOLF_COURSE_CREATE_RESET = 'GOLF_COURSE_CREATE_RESET'

export const GOLF_COURSE_NEW_CREATED_REQUEST = 'GOLF_COURSE_NEW_CREATED_REQUES'
export const GOLF_COURSE_NEW_CREATED_SUCCESS = 'GOLF_COURSE_NEW_CREATED_SUCCESS'
export const GOLF_COURSE_NEW_CREATED_FAIL = 'GOLF_COURSE_NEW_CREATED_FAIL'



export const GOLF_COURSE_DELETE_REQUEST = 'GOLF_COURSE_DELETE_REQUEST'
export const GOLF_COURSE_DELETE_SUCCESS = 'GOLF_COURSE_DELETE_SUCCESS'
export const GOLF_COURSE_DELETE_FAIL = 'GOLF_COURSE_DELETE_FAIL'
export const GOLF_COURSE_DELETE_RESET = 'GOLF_COURSE_DELETE_RESET'

export const GOLF_COURSE_UPDATE_REQUEST = 'GOLF_COURSE_UPDATE_REQUEST'
export const GOLF_COURSE_UPDATE_SUCCESS = 'GOLF_COURSE_UPDATE_SUCCESS'
export const GOLF_COURSE_UPDATE_FAIL = 'GOLF_COURSE_UPDATE_FAIL'
export const GOLF_COURSE_UPDATE_RESET = 'GOLF_COURSE_UPDATE_RESET'



export const TEE_COLOR_LIST_REQUEST = 'TEE_COLOR_LIST_REQUEST'
export const TEE_COLOR_LIST_SUCCESS = 'TEE_COLOR_LIST_SUCCESS'
export const TEE_COLOR_LIST_FAIL = 'TEE_COLOR_LIST_FAIL'

export const TEE_COLOR_UPDATE_REQUEST = 'TEE_COLOR_UPDATE_REQUEST'
export const TEE_COLOR_UPDATE_SUCCESS = 'TEE_COLOR_UPDATE_SUCCESS'
export const TEE_COLOR_UPDATE_FAIL = 'TEE_COLOR_UPDATE_FAIL'
export const TEE_COLOR_UPDATE_RESET = 'TEE_COLOR_UPDATE_RESET'

export const TEE_COLOR_CREATE_REQUEST = 'TEE_COLOR_CREATE_REQUEST'
export const TEE_COLOR_CREATE_SUCCESS = 'TEE_COLOR_CREATE_SUCCESS'
export const TEE_COLOR_CREATE_FAIL = 'TEE_COLOR_CREATE_FAIL'
export const TEE_COLOR_CREATE_RESET = 'TEE_COLOR_CREATE_RESET'

export const TEE_COLOR_DELETE_REQUEST = 'TEE_COLOR_DELETE_REQUEST'
export const TEE_COLOR_DELETE_SUCCESS = 'TEE_COLOR_DELETE_SUCCESS'
export const TEE_COLOR_DELETE_FAIL = 'TEE_COLOR_DELETE_FAIL'
export const TEE_COLOR_DELETE_RESET = 'TEE_COLOR_DELETE_RESET'

export const TEE_UPDATE_REQUEST = 'TEE_UPDATE_REQUEST'
export const TEE_UPDATE_SUCCESS = 'TEE_UPDATE_SUCCESS'
export const TEE_UPDATE_FAIL = 'TEE_UPDATE_FAIL'
export const TEE_UPDATE_RESET = 'TEE_UPDATE_RESET'







