export const HOLE_LIST_REQUEST = 'HOLE_LIST_REQUEST'
export const HOLE_LIST_SUCCESS = 'HOLE_LIST_SUCCESS'
export const HOLE_LIST_FAIL = 'HOLE_LIST_FAIL'

export const HOLE_UPDATE_REQUEST = 'HOLE_UPDATE_REQUEST'
export const HOLE_UPDATE_SUCCESS = 'HOLE_UPDATE_SUCCESS'
export const HOLE_UPDATE_FAIL = 'HOLE_UPDATE_FAIL'
export const HOLE_UPDATE_RESET = 'HOLE_UPDATE_RESET'

export const HOLE_CREATE_REQUEST = 'HOLE_CREATE_REQUEST'
export const HOLE_CREATE_SUCCESS = 'HOLE_CREATE_SUCCESS'
export const HOLE_CREATE_FAIL = 'HOLE_CREATE_FAIL'
export const HOLE_CREATE_RESET = 'HOLE_CREATE_RESET'

export const NINE_HOLE_CREATE_REQUEST = 'NINE_HOLE_CREATE_REQUEST'
export const NINE_HOLE_CREATE_SUCCESS = 'NINE_HOLE_CREATE_SUCCESS'
export const NINE_HOLE_CREATE_FAIL = 'NINE_HOLE_CREATE_FAIL'
export const NINE_HOLE_CREATE_RESET = 'NINE_HOLE_CREATE_RESET'

export const EIGHTEEN_HOLE_CREATE_REQUEST = 'EIGHTEEN_HOLE_CREATE_REQUEST'
export const EIGHTEEN_HOLE_CREATE_SUCCESS = 'EIGHTEEN_HOLE_CREATE_SUCCESS'
export const EIGHTEEN_HOLE_CREATE_FAIL = 'EIGHTEEN_HOLE_CREATE_FAIL'
export const EIGHTEEN_HOLE_CREATE_RESET = 'EIGHTEEN_HOLE_CREATE_RESET'

export const HOLE_DELETE_REQUEST = 'HOLE_DELETE_REQUEST'
export const HOLE_DELETE_SUCCESS = 'HOLE_DELETE_SUCCESS'
export const HOLE_DELETE_FAIL = 'HOLE_DELETE_FAIL'
export const HOLE_DELETE_RESET = 'HOLE_DELETE_RESET'



export const HOLES_BATCH_UPDATE_REQUEST = 'HOLES_BATCH_UPDATE_REQUEST'
export const HOLES_BATCH_UPDATE_SUCCESS = 'HOLES_BATCH_UPDATE_SUCCESS'
export const HOLES_BATCH_UPDATE_FAIL = 'HOLES_BATCH_UPDATE_FAIL'
export const HOLES_BATCH_UPDATE_RESET = 'HOLES_BATCH_UPDATE_RESET'

