export const ROUND_LIST_REQUEST = 'ROUND_LIST_REQUEST'
export const ROUND_LIST_SUCCESS = 'ROUND_LIST_SUCCESS'
export const ROUND_LIST_FAIL = 'ROUND_LIST_FAIL'

export const ROUND_DETAILS_REQUEST = 'ROUND_DETAILS_REQUEST'
export const ROUND_DETAILS_SUCCESS = 'ROUND_DETAILS_SUCCESS'
export const ROUND_DETAILS_FAIL = 'ROUND_DETAILS_FAIL'

export const ROUND_CREATE_REQUEST = 'ROUND_CREATE_REQUEST'
export const ROUND_CREATE_SUCCESS = 'ROUND_CREATE_SUCCESS'
export const ROUND_CREATE_FAIL = 'ROUND_CREATE_FAIL'