export const TEE_BOX_BULK_UPDATE_REQUEST = 'TEE_BOX_BULK_UPDATE_REQUEST'
export const TEE_BOX_BULK_UPDATE_SUCCESS = 'TEE_BOX_BULK_UPDATE_SUCCESS'
export const TEE_BOX_BULK_UPDATE_FAIL = 'TEE_BOX_BULK_UPDATE_FAIL'