export const TEE_BOX_DETAILS_REQUEST = 'TEE_BOX_DETAILS_REQUEST'
export const TEE_BOX_DETAILS_SUCCESS = 'TEE_BOX_DETAILS_SUCCESS'
export const TEE_BOX_DETAILS_FAIL = 'TEE_BOX_DETAILS_FAIL'

export const TEE_BOX_UPDATE_REQUEST = 'TEE_BOX_UPDATE_REQUEST'
export const TEE_BOX_UPDATE_SUCCESS = 'TEE_BOX_UPDATE_SUCCESS'
export const TEE_BOX_UPDATE_FAIL = 'TEE_BOX_UPDATE_FAIL'
export const TEE_BOX_UPDATE_RESET = 'TEE_BOX_UPDATE_RESET'

export const TEE_BOX_DELETE_REQUEST = 'TEE_BOX_DELETE_REQUEST'
export const TEE_BOX_DELETE_SUCCESS = 'TEE_BOX_DELETE_SUCCESS'
export const TEE_BOX_DELETE_FAIL = 'TEE_BOX_DELETE_FAIL'
export const TEE_BOX_DELETE_RESET = 'TEE_BOX_DELETE_RESET'

export const TEE_BOX_BULK_UPDATE_REQUEST = 'TEE_BOX_BULK_UPDATE_REQUEST'
export const TEE_BOX_BULK_UPDATE_SUCCESS = 'TEE_BOX_BULK_UPDATE_SUCCESS'
export const TEE_BOX_BULK_UPDATE_FAIL = 'TEE_BOX_BULK_UPDATE_FAIL'