export const TEE_LIST_REQUEST = 'TEE_LIST_REQUEST'
export const TEE_LIST_SUCCESS = 'TEE_LIST_SUCCESS'
export const TEE_LIST_FAIL = 'TEE_LIST_FAIL'

export const COURSE_TEE_LIST_REQUEST = 'COURSE_TEE_LIST_REQUEST'
export const COURSE_TEE_LIST_SUCCESS = 'COURSE_TEE_LIST_SUCCESS'
export const COURSE_TEE_LIST_FAIL = 'COURSE_TEE_LIST_FAIL'


export const TEE_UPDATE_REQUEST = 'TEE_UPDATE_REQUEST'
export const TEE_UPDATE_SUCCESS = 'TEE_UPDATE_SUCCESS'
export const TEE_UPDATE_FAIL = 'TEE_UPDATE_FAIL'
export const TEE_UPDATE_RESET = 'TEE_UPDATE_RESET'

export const TEE_ADDED_TO_HOLES_REQUEST = 'TEE_ADDED_TO_HOLES_REQUEST'
export const TEE_ADDED_TO_HOLES_SUCCESS = 'TEE_ADDED_TO_HOLES_SUCCESS'
export const TEE_ADDED_TO_HOLES_FAIL = 'TEE_ADDED_TO_HOLES_FAIL'


export const TEE_BATCH_CREATE_REQUEST = 'TEE_BATCH_CREATE_REQUEST'
export const TEE_BATCH_CREATE_SUCCESS = 'TEE_BATCH_CREATE_SUCCESS'
export const TEE_BATCH_CREATE_FAIL = 'TEE_BATCH_CREATE_FAIL'
export const TEE_BATCH_CREATE_RESET = 'TEE_BATCH_CREATE_RESET'

export const TEE_BATCH_DELETE_REQUEST = 'TEE_BATCH_DELETE_REQUEST'
export const TEE_BATCH_DELETE_SUCCESS = 'TEE_BATCH_DELETE_SUCCESS'
export const TEE_BATCH_DELETE_FAIL = 'TEE_BATCH_DELETE_FAIL'
export const TEE_BATCH_DELETE_RESET = 'TEE_BATCH_DELETE_RESET'