# Generated by Django 4.2.2 on 2023-06-15 19:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GolfCourse",
            fields=[
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                (
                    "numOfHoles",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(18),
                            django.core.validators.MinValueValidator(9),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Name of this hole (optional)",
                    ),
                ),
                (
                    "par",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(3),
                        ]
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="holes",
                        to="base.golfcourse",
                    ),
                ),
            ],
            options={
                "unique_together": {("number", "course"), ("name", "course")},
            },
        ),
        migrations.CreateModel(
            name="TeeColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("colors", models.CharField(max_length=255, null=True)),
                ("yards", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="golfcourse",
            name="tee_colors",
            field=models.ManyToManyField(related_name="courses", to="base.teecolor"),
        ),
        migrations.AddField(
            model_name="golfcourse",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Tee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GOLD", "Gold"),
                            ("BLACK", "Black"),
                            ("BLUE", "Blue"),
                            ("WHITE", "White"),
                            ("RED", "Red"),
                            ("YELLOW", "Yellow"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "yards",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                (
                    "hole",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tees",
                        to="base.hole",
                    ),
                ),
            ],
            options={
                "unique_together": {("color", "hole")},
            },
        ),
    ]
