# Generated by Django 4.2.2 on 2023-07-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_friendrequest_friendlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendrequest",
            name="timestamp",
        ),
    ]
