# Generated by Django 4.2.2 on 2023-06-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_rename_tee_colors_golfcourse_teecolors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="golfcourse",
            name="teecolors",
        ),
        migrations.AddField(
            model_name="golfcourse",
            name="tee_colors",
            field=models.ManyToManyField(related_name="teeColor", to="base.teecolor"),
        ),
    ]
