# Generated by Django 4.2.2 on 2023-07-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_tee_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teecolor",
            old_name="yards",
            new_name="back_nine_yards",
        ),
        migrations.AddField(
            model_name="teecolor",
            name="front_nine_yards",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teecolor",
            name="total_yards",
            field=models.IntegerField(default=0),
        ),
    ]
