# Generated by Django 4.2.2 on 2023-07-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_profile_delete_friendlist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FriendRequest",
        ),
    ]
