# Generated by Django 4.2.2 on 2023-06-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_remove_golfcourse_teecolors_golfcourse_tee_colors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfcourse",
            name="tee_colors",
            field=models.ManyToManyField(related_name="teeColors", to="base.teecolor"),
        ),
    ]
