# Generated by Django 4.2.2 on 2023-07-14 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_rename_yards_teecolor_back_nine_yards_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roundstats",
            name="yards_out",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
