# Generated by Django 4.2.2 on 2023-06-15 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_golfcourse_tee_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="teecolor",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course",
                to="base.golfcourse",
            ),
        ),
    ]
