# Generated by Django 4.2.2 on 2023-07-14 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_roundstats_yards_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roundstats",
            name="yards_out",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
