# Generated by Django 4.2.2 on 2023-06-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_teecolor_course"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TeeColor",
            new_name="Review",
        ),
        migrations.RemoveField(
            model_name="golfcourse",
            name="tee_colors",
        ),
        migrations.AddField(
            model_name="golfcourse",
            name="review",
            field=models.ManyToManyField(related_name="review", to="base.review"),
        ),
    ]
