# Generated by Django 4.2.2 on 2023-07-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_friendrequestnotification_delete_friendship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequestnotification",
            name="action",
            field=models.IntegerField(
                choices=[(1, "REQUEST"), (2, "ACCEPT"), (3, "UNFRIEND")]
            ),
        ),
        migrations.AlterField(
            model_name="friendrequestnotification",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests_received",
                to="base.profile",
            ),
        ),
        migrations.AlterField(
            model_name="friendrequestnotification",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests_sent",
                to="base.profile",
            ),
        ),
    ]
