# Generated by Django 4.2.2 on 2023-07-19 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_friendrequestnotification_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequestnotification",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_requests_received",
                to="base.profile",
            ),
        ),
        migrations.AlterField(
            model_name="friendrequestnotification",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_requests_sent",
                to="base.profile",
            ),
        ),
    ]
