# Generated by Django 4.2.2 on 2023-06-15 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_golfcourse_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.golfcourse",
            ),
        ),
    ]
