# Generated by Django 4.2.2 on 2023-06-15 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_review_course"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Review",
            new_name="TeeColor",
        ),
    ]
