# Generated by Django 4.2.2 on 2023-07-20 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_friendrequestnotification_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hole",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.golfcourse",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="profile_friends", to="base.profile"
            ),
        ),
    ]
