# Generated by Django 4.2.2 on 2023-06-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_rename__id_golfcourse_course_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="hole",
            name="TeeColor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.teecolor",
            ),
        ),
        migrations.AlterField(
            model_name="hole",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.golfcourse",
            ),
        ),
    ]
