# Generated by Django 4.2.2 on 2023-08-03 21:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_hole_course_alter_profile_friends"),
    ]

    operations = [
        migrations.RenameField(
            model_name="golfcourse",
            old_name="numOfHoles",
            new_name="num_of_holes",
        ),
        migrations.RemoveField(
            model_name="hole",
            name="par",
        ),
        migrations.AddField(
            model_name="hole",
            name="handicap",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tee",
            name="par",
            field=models.IntegerField(
                default=4,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(3),
                ],
            ),
        ),
        migrations.CreateModel(
            name="TeeBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=255, null=True)),
                ("front_nine_yards", models.IntegerField(default=0)),
                ("back_nine_yards", models.IntegerField(default=0)),
                ("total_yards", models.IntegerField(default=0)),
                ("slope", models.IntegerField(default=0)),
                ("handicap", models.IntegerField(default=0)),
                ("par", models.IntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.golfcourse",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="round",
            name="teeColorUsed",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.teebox"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="color",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.teebox"
            ),
        ),
        migrations.DeleteModel(
            name="TeeColor",
        ),
    ]
