# Generated by Django 4.2.2 on 2023-06-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_hole_teecolor_alter_hole_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hole",
            old_name="TeeColor",
            new_name="teeColor",
        ),
    ]
