# Generated by Django 4.2.2 on 2023-06-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_rename_teecolor_hole_teecolor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hole",
            old_name="teeColor",
            new_name="tee_color",
        ),
    ]
