# Generated by Django 4.2.2 on 2023-06-17 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_rename_teecolor_hole_tee_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tee",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.teecolor",
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="base.hole"
            ),
        ),
    ]
