# Generated by Django 4.2.2 on 2023-09-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_alter_teebox_back_nine_yards_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teebox",
            name="color",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
