# Generated by Django 4.2.2 on 2023-06-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_alter_tee_color_alter_tee_hole"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hole",
            name="tee_color",
        ),
    ]
