# Generated by Django 4.2.2 on 2023-09-18 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_alter_teebox_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hole",
            name="handicap",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="tee",
            name="par",
            field=models.IntegerField(
                default=4,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="yards",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
