# Generated by Django 4.2.2 on 2023-06-17 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_remove_hole_tee_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="hole",
            name="tee_color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.teecolor",
            ),
        ),
    ]
