# Generated by Django 4.2.2 on 2023-06-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_hole_tee_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hole",
            name="tee_color",
        ),
    ]
