# Generated by Django 4.2.2 on 2023-06-17 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_remove_hole_tee_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teecolor",
            name="colors",
        ),
        migrations.AddField(
            model_name="teecolor",
            name="color",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="base.tee"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="color",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
