# Generated by Django 4.2.2 on 2023-10-10 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_holescore_fairway_hit"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
