# Generated by Django 4.2.2 on 2023-06-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_remove_teecolor_colors_teecolor_color_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tee",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="teecolor",
            name="color",
        ),
        migrations.AddField(
            model_name="teecolor",
            name="colors",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tee",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.teecolor",
            ),
        ),
    ]
