# Generated by Django 4.2.2 on 2023-06-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_alter_hole_unique_together_remove_hole_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hole",
            unique_together=set(),
        ),
    ]
