# Generated by Django 4.2.2 on 2023-06-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_alter_hole_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="tee",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.golfcourse",
            ),
        ),
    ]
