# Generated by Django 4.2.2 on 2023-06-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_tee_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tee",
            name="course",
        ),
    ]
