# Generated by Django 4.2.2 on 2023-06-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0025_remove_tee_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="teecolor",
            name="added_to_holes",
            field=models.BooleanField(default=False),
        ),
    ]
