# Generated by Django 4.2.2 on 2023-06-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0026_teecolor_added_to_holes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoundStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.golfcourse",
                    ),
                ),
                (
                    "teeColorUsed",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.teecolor",
                    ),
                ),
                (
                    "teeUsed",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.tee",
                    ),
                ),
            ],
        ),
    ]
