# Generated by Django 4.2.2 on 2023-06-23 16:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0028_remove_roundstats_teeused_roundstats_user_holestats"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HoleStats",
            new_name="HoleScore",
        ),
        migrations.RenameModel(
            old_name="RoundStats",
            new_name="Round",
        ),
    ]
