# Generated by Django 4.2.2 on 2023-06-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0029_rename_holestats_holescore_rename_roundstats_round"),
    ]

    operations = [
        migrations.RenameField(
            model_name="holescore",
            old_name="score",
            new_name="strokes",
        ),
    ]
