# Generated by Django 4.2.2 on 2023-06-28 19:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0030_rename_score_holescore_strokes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoundStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "totalStrokes",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(200),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                (
                    "totalPutts",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(200),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                (
                    "totalCoursePar",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(200),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                (
                    "roundStat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.round",
                    ),
                ),
            ],
        ),
    ]
