# Generated by Django 4.2.2 on 2023-06-28 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0032_roundstats_totaldistance"),
    ]

    operations = [
        migrations.AddField(
            model_name="roundstats",
            name="totalHoles",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(18),
                    django.core.validators.MinValueValidator(9),
                ],
            ),
        ),
    ]
